### PR TITLE
Add table creation to examples.

### PR DESCRIPTION
**Pull request by kinware**
To make it easier for people to run the examples "as is" we could add automatic table creation.

This PR does this for the first basic example.

Should this be a separate example? Should we add it to all of them? I can do either.

Thoughts @fantix?

### CODE REVIEW

**Comment by fantix** [comment]
Thanks for the PR! This actually requires additional `psycopg2` installed to run, which may or may not be a trouble. I was thinking of moving the short examples into documentation as a part of the tutorial, and replace `examples` with a more complete example project. But those need some time which is not sufficient to me ATM, so for now I think it is okay to merge this PR. 😸  Run `basic.py` first and the rest are good to go, install `psycopg2` when error is met, should be enough for a couple of weeks.

**Comment by kinware** [comment]
Good catch on psycopg2 dependency! Could add a comment about that fact?

**Comment by fantix** [comment]
Yeah please do.

**Comment by kinware** [comment]
Done. Added dispose() of the non-async engine too to keep things clean.

**Comment by fantix** [comment]
Merged.

**Pull request closed without merging**
